export const XbarRDialog = ref(false)
export const XbarSDialog = ref(false)
export const XbarDialog = ref(false)
export const RDialog = ref(false)
export const SDialog = ref(false)

export const IMRDialog = ref(false)
export const IDialog = ref(false)
export const MRDialog = ref(false)

export const PDialog = ref(false)
export const LaneyPDialog = ref(false)
export const NPDialog = ref(false)
export const UDialog = ref(false)
export const LaneyUDialog = ref(false)
export const CDialog = ref(false)
